name: Build GitBook

on:
  push:
    branches:
      - source

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [12.x]

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install GitBook
      run: npm install -g gitbook-cli --registry=https://registry.npm.taobao.org

    - name: Checkout branch to source
      uses: actions/checkout@v1
      with:
        ref: source

    - name: Install GitBook Dependencies
      run: gitbook install --registry=https://registry.npm.taobao.org

    - name: Build GitBook
      run: gitbook build . docs

    - name: Publish
      run: |
        git config --global user.email "${GITHUB_ACTOR}"
        git config --global user.name "${GITHUB_ACTOR}"
        REPOSITORY_PATH="https://${ACCESS_TOKEN:-"x-access-token:$GITHUB_TOKEN"}@github.com/${GITHUB_REPOSITORY}.git"
        git add -f docs
        git commit -m "Deploying to ${BRANCH} from ${BASE_BRANCH:-master} ${GITHUB_SHA}" --quiet
        git push $REPOSITORY_PATH `git subtree split --prefix docs ${BASE_BRANCH:-master}`:$BRANCH --force
      shell: bash
      env:
        ACCESS_TOKEN: ${{ secrets.hlyani }}
        BASE_BRANCH: source
        BRANCH: master
